// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl0mxEPl4xZ2Y4O3yeq2ewNinJXAXWRvA',
    appId: '1:755980243469:web:9762471e85083037ccbb44',
    messagingSenderId: '755980243469',
    projectId: 'background-remover-bfd68',
    authDomain: 'background-remover-bfd68.firebaseapp.com',
    storageBucket: 'background-remover-bfd68.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqHn2IH4EUhUMdJEnOjo6i6s5pf-0bssA',
    appId: '1:755980243469:android:cd2f77ebda764dd5ccbb44',
    messagingSenderId: '755980243469',
    projectId: 'background-remover-bfd68',
    storageBucket: 'background-remover-bfd68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb8xPmJgchGSjdgz51Bzitnw_MEuNqUCA',
    appId: '1:755980243469:ios:4c4fe885d8495db0ccbb44',
    messagingSenderId: '755980243469',
    projectId: 'background-remover-bfd68',
    storageBucket: 'background-remover-bfd68.appspot.com',
    iosClientId: '755980243469-0gpk00a8u19hughccpmj1nmbda108a1l.apps.googleusercontent.com',
    iosBundleId: 'com.example.backgroundRemover',
  );
}
