// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl0mxEPl4xZ2Y4O3yeq2ewNinJXAXWRvA',
    appId: '1:755980243469:web:9762471e85083037ccbb44',
    messagingSenderId: '755980243469',
    projectId: 'background-remover-bfd68',
    authDomain: 'background-remover-bfd68.firebaseapp.com',
    storageBucket: 'background-remover-bfd68.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSie2j_0_pxhBdk-ycgC0X0aFAjb2wA_0',
    appId: '1:906181049338:android:e8ee7246927341fc0b8243',
    messagingSenderId: '906181049338',
    projectId: 'remove-bg-9850c',
    storageBucket: 'remove-bg-9850c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMs8pv2nTrsCi0RlEpCGn-4jSv8_BbAtw',
    appId: '1:906181049338:ios:0692cd6e205b218f0b8243',
    messagingSenderId: '906181049338',
    projectId: 'remove-bg-9850c',
    storageBucket: 'remove-bg-9850c.appspot.com',
    iosBundleId: 'com.example.removeBg',
  );

}